POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaSIsImlkIjoiNWVkYWMwZDYzMzdkM2QwYzlmZDA0NWIyIiwiaWF0IjoxNTkxMzk1MjY5fQ.PICPjN1g7A2-i-kzYNs17_5YydsPkeJ_sR3YwfWtKkc

{
  "title": "new post! 2",
  "author": "yo",
  "url": "String",
  "likes": 9999999
}